CollectionWebApp/CollectionWebApp/Models/Item.cs
using System.Text.Json.Serialization;

namespace CollectionWebApp.Models
{
    public class Item
    {
        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public DateTime Created { get; set; }

        public int UserCollectionId { get; set; }
        [JsonIgnore]
        public virtual UserCollection UserCollection { get; set; } = null!;

        [JsonIgnore]
        public virtual ICollection<Tag> Tags { get; set; } = null!;
        [JsonIgnore]
        public virtual ICollection<TagItem> TagItems { get; set; } = null!;

        [JsonIgnore]
        public virtual ICollection<Field> Fields { get; set; } = null!;
        [JsonIgnore]
        public virtual ICollection<FieldItem> FieldItems { get; set; } = null!;

        [JsonIgnore]
        public virtual ICollection<Like> Likes { get; set; } = null!;

        [JsonIgnore]
        public virtual ICollection<Commentary> Commentaries { get; set; } = null!;
    }
}

CollectionWebApp/CollectionWebApp/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;

using CollectionWebApp.Models;
using CollectionWebApp.ViewModels;
using CollectionWebApp.Extensions;

namespace CollectionWebApp.Controllers
{
    public class ItemController : Controller
    {
        private AppDbContext db;

        public ItemController(AppDbContext db)
        {
            this.db = db;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int? id)
        {
            Item? item = await db.Items.FindAsync(id);
            var model = CreateIndexModel(item, User.HasAccessToItem(item, db));
            return model == null ? NotFound() : View(model);
        }

        private ItemIndexModel? CreateIndexModel(Item? item, bool changeAllowed = false)
        {
            if (item == null) return null;
            return new() { Item = item, ChangeAllowed = changeAllowed, User = User.GetAppUser(db) };
        }

        [HttpGet]
        public async Task<IActionResult> Create(int? id)
        {
            UserCollection? collection = await db.UserCollections.FindAsync(id);
            if (!User.HasAccessToCollection(collection, db)) return NotFound();
            var model = CreateCreateModel(collection);
            return model == null ? NotFound() : View(model);
        }

        private ItemCreateModel? CreateCreateModel(UserCollection? collection)
        {
            if (collection == null) return null;
            return new()
            {
                UserCollectionId = collection.Id,
                Name = String.Empty
            };
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ItemCreateModel model)
        {
            if (!User.HasAccessToCollection(model.UserCollectionId, db)) return NotFound();
            if (!ModelState.IsValid) return View(model);
            var item = await CreateItem(model);
            return RedirectToAction("Edit", "Item", new {id = item.Id});
        }

        private async Task<Item> CreateItem(ItemCreateModel model)
        {
            var collection = await db.UserCollections.FindAsync(model.UserCollectionId);
            var item = new Item()
            {
                UserCollection = collection,
                Name = model.Name,
            };
            await db.Items.AddAsync(item);
            await db.SaveChangesAsync();
            return item;
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            var item = await db.Items.FindAsync(id);
            if (!User.HasAccessToItem(item, db)) return NotFound();
            var model = CreateEditModel(item);
            return model == null ? NotFound() : View(model);
        }

        private ItemEditModel? CreateEditModel(Item? item)
        {
            if (item == null) return null;
            ICollection<Field> fields = item!.UserCollection?.Fields ?? new List<Field>();
            ICollection<FieldItem> fieldItems = new List<FieldItem>();
            int fieldsAmount = fields.Count;
            foreach(var field in fields)
            {
                var fieldItem = field.FieldItems.FirstOrDefault(fi => fi.Item == item);
                if (fieldItem == null)
                {
                    fieldItem = new FieldItem() { Field = field, Item = item };
                    db.FieldItems.Add(fieldItem);
                    db.SaveChanges();
                }
                fieldItems.Add(fieldItem);
            }
            return new()
            {
                ItemId = item.Id,
                UserCollectionId = item.UserCollectionId,
                Name = item.Name,
                FieldItems = fieldItems.Select(fi => CreateFieldItemModel(fi)).ToList<FieldItemModel>()
            };
        }

        private FieldItemModel CreateFieldItemModel(FieldItem fi)
        {
            return new()
            {
                ItemId = fi.ItemId,
                FieldId = fi.FieldId,
                FieldName = fi.Field.Name,
                Type = fi.Field.Type,
                BoolValue = fi.BoolValue,
                DateValue = fi.DateValue,
                NumberValue = fi.NumberValue,
                StringValue = fi.StringValue,
                TextValue = fi.TextValue
            };
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ItemEditModel model)
        {
            if (!User.HasAccessToItem(model.ItemId, db)) return NotFound();
            if (!ModelState.IsValid) return View(model);
            var item = await db.Items.FindAsync(model.ItemId);
            await EditItem(item, model);
            return RedirectToAction("Edit", "Item", new { id = item?.Id });
        }

        private async Task EditItem(Item? item, ItemEditModel model)
        {
            if (item == null) return;
            item.Name = model.Name;
            foreach(var fi in model.FieldItems)
            {
                await EditFieldItem(fi);
            }
            await db.SaveChangesAsync();
        }
        
        private async Task EditFieldItem(FieldItemModel model)
        {
            var fi = await db.FieldItems.FindAsync(model.FieldId, model.ItemId);
            if (fi == null) return;
            fi.TextValue = model.TextValue;
            fi.BoolValue = model.BoolValue;
            fi.NumberValue = model.NumberValue;
            fi.DateValue = model.DateValue;
            fi.StringValue = model.StringValue;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {
            var item = await db.Items.FindAsync(id);
            if (!User.HasAccessToItem(item, db)) return NotFound();
            db.Items.Remove(item!);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Collection", new { id = item?.UserCollection?.Id });
        }
    }
}

CollectionWebApp/CollectionWebApp/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;

using CollectionWebApp.Models;
using CollectionWebApp.Extensions;

namespace CollectionWebApp.Controllers
{
    public class TagController : Controller
    {
        private AppDbContext db;

        public TagController(AppDbContext db)
        {
            this.db = db;
        }

        [HttpGet]
        public IActionResult Search(string term)
        {
            var result = term == null ? db.Tags : db.Tags.Where(t => t.Name.StartsWith(term));
            return Json(result.ToList());
        }

        [HttpGet]
        public IActionResult GetItemTags(int id)
        {
            var result = db.TagItems.Where(ti => ti.ItemId == id).Select(ti => new { ti.Tag.Name, ti.TagId });
            return Json(result.ToList());
        }

        [HttpPost]
        public async Task<IActionResult> PostItemTags([FromBody] TagsModel model)
        {
            var item = await db.Items.FindAsync(model.ItemId);
            if (!User.HasAccessToItem(item, db)) return Json(false);
            await DeleteTagItems(item!);
            foreach(var tag in model.Tags)
            {
                var dbTag = await FindTag(tag);
                if (dbTag == null)
                {
                    dbTag = new Tag() { Name = tag.Name };
                    await db.Tags.AddAsync(dbTag);
                    await db.SaveChangesAsync();
                }
                await db.TagItems.AddAsync(new TagItem() { Tag = dbTag, Item = item! });
                await db.SaveChangesAsync();
            }
            return Json(true);
        }

        private async Task<Tag?> FindTag(TagModel model)
        {
            return await db.Tags.FindAsync(model.Id) ?? db.Tags.FirstOrDefault(t => t.Name == model.Name);
        }

        private async Task DeleteTagItems(Item item)
        {
            var tagItems = db.TagItems.Where(ti => ti.Item == item);
            db.TagItems.RemoveRange(tagItems);
            await db.SaveChangesAsync();
        }
    }

    public class TagModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class TagsModel
    {
        public TagModel[] Tags { get; set; }
        
        public int ItemId { get; set; }
    }
}

CollectionWebApp/CollectionWebApp/Views/Item/Create.cshtml
@model CollectionWebApp.ViewModels.ItemCreateModel
@{
    ViewData["Title"] = "Create item";
}

<h1>@ViewData["Title"]</h1>

<div class="validation" asp-validation-summary="All"></div>
<form asp-action="Create" asp-controller="Item" asp-anti-forgery="true">
    <input hidden asp-for="UserCollectionId" />
    <div class="form-group p-2">
        <label asp-for="Name">Name</label>
        <input class="form-control" asp-for="Name">
    </div>
    <button class="btn btn-primary p-2" type="submit">Submit</button>
    <a class="btn btn-secondary p-2" asp-action="Index" asp-controller="Collection" asp-route-id="@Model.UserCollectionId">Cancel</a>
</form>

CollectionWebApp/CollectionWebApp/Views/Item/Edit.cshtml
@model CollectionWebApp.ViewModels.ItemEditModel
@{
    ViewData["Title"] = "Edit item";
}

@section Head
{

}

<h1>@ViewData["Title"]</h1>

<div class="validation" asp-validation-summary="All"></div>
<form asp-action="Edit" asp-controller="Item" asp-anti-forgery="true" id="form">
    <input hidden asp-for="ItemId" />
    <input hidden asp-for="UserCollectionId" />
    <div class="form-group p-2">
        <label asp-for="Name">Name</label>
        <input class="form-control" asp-for="Name">
    </div>
    <div class="form-group p-2">
        <label asp-for="FieldItems">Fields</label>
        @Html.EditorFor(m => m.FieldItems)
    </div>
    <div class="form-group p-2">
        <label>Tags</label>
        <select class="form-control" multiple="multiple" id="select2">

        </select>
        <input class="btn btn-secondary p-2 my-2" id="saveTagsBtn" value="Save">
        <div id="ajaxResult" class="text-muted p-2 my-2"></div>
    </div>
    <button class="btn btn-primary p-2" type="submit">Submit</button>
    <a class="btn btn-secondary p-2" asp-action="Index" asp-controller="Collection" asp-route-id="@Model.UserCollectionId">Cancel</a>
</form>

@section Scripts
{
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#select2').select2({
                tags: true,
                ajax: {
                    type: 'GET',
                    url: '/Tag/Search',
                    processResults: function(data){
                        return {
                            results: $.map(data, function(item){
                                return {
                                    text: item.name,
                                    id: item.id
                                }
                            })
                        };
                    }
                }
            });

            var select = $('#select2');
            $.ajax({
                type: 'GET',
                url: '@Url.Action("GetItemTags","Tag", new { id = Model.ItemId })'
            }).then(function (data) {
                //create the option and append to Select2
                data.forEach(function(item){
                    var option = new Option(item.name, item.tagId, true, true);
                    select.append(option).trigger('change');
                });

                select.trigger({
                    type: 'select2:select',
                    params: {
                        data: data
                    }
                });
            });

            $('#saveTagsBtn').click(function(event){
                var data = select.select2('data');
                var objects = data.map(function(item){
                    return {
                        'Name': item.text,
                        'Id': item.id === item.text ? 0 : item.Id
                    }
                });
                var tags = {
                    'Tags': objects,
                    'ItemId': @Model.ItemId 
                }

                $.ajax({
                    url: '@Url.Action("PostItemTags","Tag")',
                    type: 'POST',
                    contentType: 'application/json',
                    dataType: 'json',
                    data: JSON.stringify(tags),
                    success: function (result) {
                        $('#ajaxResult').text(result ? 'Saved successfully' : 'Not saved');
                    }
                });
            });
        });
    </script>
}

CollectionWebApp/CollectionWebApp/Views/Item/Index.cshtml
@model CollectionWebApp.ViewModels.ItemIndexModel

@section Head{
    <!--Bootstrap Icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
}

@{
    ViewData["Title"] = "Item Page";
}

<h1>@ViewData["Title"]</h1>

<div class="text-center">
    <div class="d-flex">
        <div class="d-flex flex-fill justify-content-center">
            <div class="card flex-fill" >
                <img src="@Model.Item.UserCollection.ImageUrl" class="align-self-center img-thumbnail p-2 m-2" alt="collection-image" style="width: 18em;">
                <div class="card-body">
                    <div class="item-data">
                        <h5 class="card-title">@Model.Item.Name</h5>
                        <p class="card-text">
                            <p class="collection-data">
                                Collection: <a asp-controller="Collection" asp-action="Index" asp-route-id="@Model.Item.UserCollection.Id">@Model.Item.UserCollection.Name</a>
                            </p>
                            @if (Model.Item.Tags.Count > 0)
                            {
                                <p class="tags">Tags: 
                                    @foreach(var tag in Model.Item.Tags)
                                    {
                                        <a href="#">@tag.Name</a>       
                                    }
                                </p>
                            }
                            else
                            {
                                <p class="tags">No tags</p>
                            }
                            <p class="fields">
                                @foreach(var field in Model.Item.UserCollection.Fields)
                                {
                                    <p class="field">
                                        @field.Name: 
                                        <p class="field-value">
                                            @field.FieldItems.FirstOrDefault(fi => fi.Item == Model.Item)?.Value
                                        </p>
                                    </p>
                                }
                            </p>
                        </p>
                    </div>
                    @if (Model.ChangeAllowed)
                    {
                        <div class="item-controls d-inline-flex">
                            <a class="btn btn-secondary" asp-controller="Item" asp-action="Edit" asp-route-id="@Model.Item.Id">Edit</a>
                            <form asp-action="Delete" asp-controller="Item" asp-route-id="@Model.Item.Id" asp-anti-forgery="true">
                                <input class="btn btn-danger" type="submit" value="Delete" />
                            </form>
                        </div>
                    }
                </div>
                <div class="card-footer">
                    <div class="likes d-flex" style="font-size: 2em;">
                        <button class="flex-fill" id="likeBtn" style="border: none; background: none;"  disabled="@(Model.User == null ? "disabled" : null)">                       
                            <div class="text-muted">
                                <div id="likeCounter"></div>
                                <i id="likeIcon" class="bi-heart" style="color: red"></i>
                            </div>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <br />

    <ul class="commentaries list-group">
        <li class="list-group-item">
            Commentaries: @Model.Item.Commentaries.Count
        </li>
        @{
            var comments = Model.Item.Commentaries.OrderBy(c => c.Created);
        }
        @foreach(var comment in comments)
        {
            <li class="list-group-item commentary d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <a class="fw-bold" asp-controller="Account" asp-action="Index" asp-route-id="@comment.User.Id">
                        @comment.User.Name
                    </a>
                    @comment.Text
                </div>                
            </li>
        }
        @if(User.Identity.IsAuthenticated)
        {
            <li class="list-group-item commentary-write">
                <form method="post" id="writeCommentForm" asp-anti-forgery="true">
                    <div class="mb-3">
                        <input type="text" class="form-control" id="userNameInput" disabled value="@Model.User!.Name" />
                    </div>
                    <div class="mb-3">
                        <textarea class="form-control" id="commentTextInput" placeholder="Write your comment here"></textarea>
                    </div>
                    <input class="btn btn-primary" type="submit" value="Submit" formtarget="writeCommentForm" id="writeCommentFormSubmitBtn">
                </form>
            </li>
        }
    </ul>
</div>

@section Scripts{
    <script type="text/javascript">
        $('document').ready(function(){
            function getLikesAmount(){
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("GetLikeAmount","Like", new {id = Model.Item.Id})',
                    success: function(result) {
                        console.log(result);
                        $('#likeCounter').text(result);
                    }
                });
            };

            function getIsLiked(){
                var data = {
                    UserId: @(Model.User?.Id ?? 0),
                    ItemId: @Model.Item.Id
                };
                $.ajax({
                    url: '@Url.Action("IsLiked","Like")',
                    type: 'POST',
                    contentType: 'application/json',
                    dataType: 'json',
                    data: JSON.stringify(data),
                    success: function(result) {
                        console.log(result);
                        $('#likeIcon').attr('class', result ? 'bi-heart-fill' : 'bi-heart');
                    }
                });
            };

            function like(){
                var data = {
                    UserId: @(Model.User?.Id ?? 0),
                    ItemId: @Model.Item.Id
                };   

                $.ajax({
                    url: '@Url.Action("Like","Like")',
                    type: 'POST',
                    contentType: 'application/json',
                    dataType: 'json',
                    data: JSON.stringify(data),
                    success: function(result){
                        console.log(result);
                        getLikesAmount();
                        getIsLiked();
                    }
                });
            };

            setInterval(function(){
                getLikesAmount();
                getIsLiked();
            },1500);

            $('#likeBtn').click(function(){
                like();
            });
        });
    </script>
}